import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
[ env ]
TERM = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 20  }
blur = true
padding.x = 10
padding.y = 10
dynamic_title = true


decorations = "Buttonless"

startup_mode = "Windowed"

#opacity = 0.1


[keyboard]
bindings = [
{ key = "N", mods = "Command|Shift", action = "CreateNewTab" },
]




[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 24

#for video
# size = 35.0
