"use strict";var b=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var O=Object.getOwnPropertyNames;var B=Object.prototype.hasOwnProperty;var _=(c,s)=>{for(var i in s)b(c,i,{get:s[i],enumerable:!0})},G=(c,s,i,g)=>{if(s&&typeof s=="object"||typeof s=="function")for(let a of O(s))!B.call(c,a)&&a!==i&&b(c,a,{get:()=>s[a],enumerable:!(g=v(s,a))||g.enumerable});return c};var F=c=>G(b({},"__esModule",{value:!0}),c);var N={};_(N,{default:()=>C});module.exports=F(N);var t=require("@raycast/api"),o=require("react"),n=require("react/jsx-runtime");function C(c){let{url:s}=c.arguments,[i,g]=(0,o.useState)(null),[a,h]=(0,o.useState)(null),[w,k]=(0,o.useState)(),[z,S]=(0,o.useState)(),[u,I]=(0,o.useState)(),[L,y]=(0,o.useState)(),[A,R]=(0,o.useState)(!0),P=e=>{let d=e.match(/<title>(.*?)<\/title>/)?.[1],p=e.match(/<meta name="description" content="(.*?)"\/>/)?.[1],m=e.match(/<meta\s+charset=["']?([a-zA-Z0-9-]+)["']?\s*\/?>/i)?.[1],f=e.match(/<html lang="(.*?)">/)?.[1]?.substring(0,2),r=e.match(/<meta name="author" content="(.*?)"\/>/)?.[1]||e.match(/<meta\s+property=["']twitter:site["']\s+content=["']@([a-zA-Z0-9_]+)["']\s*\/?>/i)?.[1],$=e.match(/<meta\s+property=["']og:image["']\s+content=["']([^"']+)["']\s*\/?>/i)?.[1];$&&y($),d&&h(l=>({...l,title:d})),p&&h(l=>({...l,description:p})),m&&h(l=>({...l,charset:m})),f&&h(l=>({...l,language:f})),r&&h(l=>({...l,author:r}))},x=e=>{let d=e.match(/<h[1-6]>(.*?)<\/h[1-6]>/g),p=e.match(/<p>(.*?)<\/p>/g),m=e.match(/<a(.*?)<\/a>/g),T=e.match(/<img(.*?)>/g),f=e.match(/<script(.*?)<\/script>/g);d&&g(r=>({...r,hTags:String(d.length)})),p&&g(r=>({...r,pTags:String(p.length)})),m&&g(r=>({...r,aTags:String(m.length)})),T&&g(r=>({...r,imgTags:String(T.length)})),f&&g(r=>({...r,scriptTags:String(f.length)}))},D=async e=>{let p=await(await fetch(e)).text(),m=`https://www.google.com/s2/favicons?domain=${e}`;k(m),x(p),P(p)},M=()=>{z&&S(void 0)},U=e=>!!new RegExp("^(https?:\\/\\/)?((([a-z\\d]([a-z\\d-]*[a-z\\d])*)\\.)+[a-z]{2,}|((\\d{1,3}\\.){3}\\d{1,3}))(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*(\\?[;&a-z\\d%_.~+=-]*)?(\\#[-a-z\\d_]*)?$","i").test(e),E=async e=>{try{return(await fetch(e)).status===200}catch{return!1}},W=async e=>{e.url&&(U(e.url)&&await E(e.url)?(await D(String(e.url)),I(e.url),R(!1)):((0,t.confirmAlert)({icon:t.Icon.ExclamationMark,title:"URL is not valid",message:"Please enter a valid URL including the protocol (http:// or https://).",primaryAction:{title:"Try another",onAction:()=>{M(),(0,t.popToRoot)({clearSearchBar:!1})}},dismissAction:{title:"Cancel",onAction:()=>{M(),(0,t.popToRoot)({clearSearchBar:!0})}}}),S("Invalid URL"),R(!1)))};return(0,o.useEffect)(()=>{s&&W({url:s})},[]),(0,n.jsxs)(n.Fragment,{children:[A&&(0,n.jsx)(t.Detail,{isLoading:!0,navigationTitle:"Getting data..."}),i&&!A&&(0,n.jsx)(t.Detail,{navigationTitle:`Scraped ${u}`,markdown:(w&&`# ![${u}](${w}) `||"#")+` Website OG Image: 
`+(L?`![${u}](${L})`:"No OG Image found")+`

## Website Info 
`+(i.hTags?`* **h-Tags:** ${i.hTags} 
`:`
`)+(i.pTags?`* **p-Tags:** ${i.pTags} 
`:`
`)+(i.aTags?`* **a-Tags:** ${i.aTags} 
`:`
`)+(i.imgTags?`* **img-Tags:** ${i.imgTags} 
`:`
`)+(i.scriptTags?`* **script-Tags:** ${i.scriptTags} 
`:`
`),metadata:(0,n.jsxs)(t.Detail.Metadata,{children:[a.title&&(0,n.jsx)(t.Detail.Metadata.Label,{title:"Page Title",text:a.title}),a.description&&(0,n.jsx)(t.Detail.Metadata.Label,{title:"Description",text:a.description}),(a.charset||a.language)&&(0,n.jsxs)(t.Detail.Metadata.TagList,{title:"Page Info",children:[a.charset&&(0,n.jsx)(t.Detail.Metadata.TagList.Item,{text:a.charset,color:"#22c55e"}),a.language&&(0,n.jsx)(t.Detail.Metadata.TagList.Item,{text:a.language,color:"#22c55e"})]}),a.author&&(0,n.jsx)(t.Detail.Metadata.Separator,{}),a.author&&(0,n.jsx)(t.Detail.Metadata.Link,{title:"Source",target:String(u),text:a.author})]}),actions:u&&(0,n.jsxs)(t.ActionPanel,{children:[(0,n.jsx)(t.Action.OpenInBrowser,{url:u,title:"Open Site"}),(0,n.jsx)(t.Action,{title:"Scrape Another Site",onAction:()=>{g(null),I(""),h(null),y(""),(0,t.popToRoot)({clearSearchBar:!1})},icon:t.Icon.Repeat}),a.title&&(0,n.jsx)(t.Action.CopyToClipboard,{title:"Copy Page Title",content:a.title,shortcut:{modifiers:["cmd","shift"],key:"t"}}),a.description&&(0,n.jsx)(t.Action.CopyToClipboard,{title:"Copy Page Description",content:a.description,shortcut:{modifiers:["cmd","shift"],key:"d"}})]})})]})}
