[Setting]
overwrite_assets        = 1
check_spicetify_upgrade = 0
current_theme           = bloom
color_scheme            = dark
inject_css              = 1
replace_colors          = 1
spotify_path            = /Applications/Spotify.app/Contents/Resources
prefs_path              = /Users/senkvs/Library/Application Support/Spotify/prefs
spotify_launch_flags    = 

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = dribbblish.js|fullAppDisplay.js|popupLyrics.js|bloom.js|bookmark.js|power-bar.js|songstats.js|keyboardShortcut.js|lastfm.js|listPlaylistsWithSong.js|quick-add-to-playlist.js|rym.js|savePlaylists.js|seekSong.js|seekSongMyKeybinds.js|sortByPlayCount.js|spotifyBackup.js|starRatings.js|volumePercentage.js|wikify.js
custom_apps           = marketplace|reddit|new-releases
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

; DO NOT CHANGE!
[Backup]
version = 1.1.97.962.g24733a46
with    = 2.14.1
